spring.application.name=makemytrip
server.port = 8080
spring.data.mongodb.uri = mongodb+srv://dbdivya:5192@main.ss410bi.mongodb.net/?appName=main
spring.data.mongodb.database = makemytrips
spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration